#!/usr/bin/env bash
# e: exit on any error, u: exit on unset vars, x: print every line, o pipefail: require entire | pipe to succeed.
set -euxo pipefail

SUBDOMAIN=lawndisorder.com

IMAGE_NAME=lawndisorder-client
IMAGE_ID=$DOCKER_REGISTRY_URL_PREFIX/$IMAGE_NAME

# Change all uppercase to lowercase
IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
# Strip git ref prefix from version
IMAGE_TAG=$GITHUB_SHA

cat deployment.yaml \
| yq '.spec.template.spec.containers[0].image="'$IMAGE_ID:$IMAGE_TAG'"' -\
| kubectl apply -f -

cat service.yaml \
| kubectl apply -f -

cat ingress.yaml \
| yq '.spec.tls[0].hosts[0]="'$SUBDOMAIN'"'  -\
| yq '.spec.rules[0].host="'$SUBDOMAIN'"' -\
| kubectl apply -f -